#+TITLE: PacmEn, Pacman made easier

* About
Pacmen is a prompt heavy and user friendly pacman.
It does not aim to replace pacman, it instead aims at providing easier to remember commands. (similar to Debian's apt)

pacmen can be used by average and advanced users alike and comes with strong defaults like
- a pager whenever a packaged is search to make it easier to read descriptions (search in pager with '/', back/next with 'N' / 'n' and quit with 'q')
- fuzzy finder to easily find packages and select it without typing the whole word.
* Requirements
- pacman
- wget (only for installation)
  - =sudo pacman -S wget=
- choose
  - =sudo pacman -S choose=
- fzf
  - =sudo pacman -S fzf=
- less
  - =sudo pacman -S less=
- yay
  - =sudo pacman -S yay=
* Installation
#+BEGIN_SRC bash
wget https://raw.githubusercontent.com/AfzGit/pacmEn/main/pacmen
chmod a+x pacmen
sudo mv pacmen /usr/bin/
#+END_SRC
* Usage
pacmen can be used in many different ways

simply typing =pacmen= will put you in prompt mode where you can select installing, removing, deleting packages etc with pacman

=pacmen i= or =pacmen install= will prompt for a package name to be installed and will search that name in the default repository.
=pacmen i firefox= or =pacmen install firefox= will install for 'firefox' without the prompt.

similarly other options like =pacmen remove= or =pacmen remove firefox= will give remove prompt or remove the specified package.

The supported options along with their pacman counter-parts are:
- View [pacmen v/V]
  - sudo pacman -Qs
- install [pacmen i/I/install]
  - sudo pacman -S
- remove [pacmen r/R/rem/remove]
  - sudo pacman -Rs
- search [pacmen s/S/search]
  - sudo pacman -Ss
  - yay -Ss
- aur [pacmen a/A/aur]
  - yay -S
- clean [pacmen c/C/clean]
  - yay --sync --clean
  - yay --clean
- update [pacmen u/U/update]
  - sudo pacman -Syyu
- -h/--help [pacmen -h/--help]
