* About
PacmEn (Pacman made Easier) is a prompt heavy, simple and user friendly pacman script.

If you are having difficulty remembering pacman options (-Rs -S -Qs -Syyu etc), then this is for you.
It does not aim to replace pacman, but it instead aims at providing easier to remember commands (similar to Debian's apt).

PacmEn can be used by average and advance users alike and comes with strong defaults like:
- a pager whenever a package is search to make it easier to read descriptions (note: search in pager with '/', back/next with 'N' / 'n' and quit with 'q')
- fuzzy finder to easily find packages and select it without typing the whole name.
* Requirements
- pacman
- wget (only for installation)
  - =sudo pacman -S wget=
- choose
  - =sudo pacman -S choose=
- fzf
  - =sudo pacman -S fzf=
- less
  - =sudo pacman -S less=
- yay
  - =sudo pacman -S yay=
* Installation
#+BEGIN_SRC bash
wget https://raw.githubusercontent.com/AfzGit/pacmEn/main/pacmen
chmod a+x pacmen
sudo mv pacmen /usr/bin/
#+END_SRC
* Usage
PacmEn can be used in many different ways

simply typing =pacmen= (pacman but with an 'e') will put you in prompt mode where you can select installing, removing, deleting packages etc with pacman

=pacmen i= or =pacmen install= will prompt the user to enter package name, this name will be searched in the default repository and then installed.
=pacmen i firefox= or =pacmen install firefox= will install 'firefox' but without the prompt.

Similarly other options like =pacmen remove= or =pacmen remove firefox= will give remove prompt or remove the specified package.

The supported options along with their pacman counter-parts are:
- View installed packages -> [sudo pacman -Qs]
  - =pacmen v/V=
- Install package -> [sudo pacman -S]
  - =pacmen i/I/install=
- Remove package -> [sudo pacman -Rs]
  - =pacmen r/R/rem/remove=
- Search packages -> [sudo pacman -Ss and yay -Ss]
  - =pacmen s/S/search=
- AUR install -> [yay -S]
  - =pacmen a/A/aur=
- Clean unused -> [yay --sync --clean and yay --clean]
  - =pacmen c/C/clean=
- Update system -> [sudo pacman -Syyu]
  - =pacmen u/U/update=

Notes:
- Entering 'e' anytime will exit pacmen
- I am not responsible for any damages you encounter using this script.
